// <auto-generated />
using System;
using HR_T3.Context.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR_T3.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230408073904_initial12")]
    partial class initial12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HR_T3.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Bilge Adam Ankara",
                            CreateDate = new DateTime(2023, 4, 8, 10, 39, 3, 499, DateTimeKind.Local).AddTicks(6220),
                            Name = "Bilge Adam Boost Team 3",
                            UpdatedDate = new DateTime(2023, 4, 8, 10, 39, 3, 499, DateTimeKind.Local).AddTicks(6236)
                        });
                });

            modelBuilder.Entity("HR_T3.Domain.Entities.Cost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Damage")
                        .HasColumnType("float");

                    b.Property<string>("File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ReplyDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeOfCost")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Costs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalStatus = 1,
                            CreateDate = new DateTime(2023, 4, 8, 10, 39, 3, 505, DateTimeKind.Local).AddTicks(6636),
                            Damage = 500.0,
                            PersonId = "59323082792",
                            ResponseDate = new DateTime(2023, 4, 7, 10, 39, 3, 505, DateTimeKind.Local).AddTicks(6642),
                            TypeOfCost = 0,
                            UpdatedDate = new DateTime(2023, 4, 8, 10, 39, 3, 505, DateTimeKind.Local).AddTicks(6640)
                        },
                        new
                        {
                            Id = 2,
                            ApprovalStatus = 2,
                            CreateDate = new DateTime(2023, 4, 8, 10, 39, 3, 505, DateTimeKind.Local).AddTicks(6690),
                            Damage = 1.0,
                            PersonId = "59323082792",
                            ReplyDate = new DateTime(2023, 4, 8, 10, 39, 3, 505, DateTimeKind.Local).AddTicks(6695),
                            ResponseDate = new DateTime(2022, 4, 8, 10, 39, 3, 505, DateTimeKind.Local).AddTicks(6693),
                            TypeOfCost = 1,
                            UpdatedDate = new DateTime(2023, 4, 8, 10, 39, 3, 505, DateTimeKind.Local).AddTicks(6691)
                        });
                });

            modelBuilder.Entity("HR_T3.Domain.Entities.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AnnualPermit")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Graduation")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastSurName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateOfWork")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "59323082791",
                            AccessFailedCount = 0,
                            Address = "adres kısmı",
                            AnnualPermit = 20,
                            Birthday = new DateTime(1989, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CompanyId = 1,
                            ConcurrencyStamp = "b46c74ca-d0e0-4fc3-a729-1fc6cc17ce30",
                            CreateDate = new DateTime(2023, 4, 8, 10, 39, 3, 499, DateTimeKind.Local).AddTicks(6702),
                            Department = 1,
                            Email = "fatmasenay.yilmazciftci@bilgeadamboost.com",
                            EmailConfirmed = true,
                            Gender = 0,
                            Graduation = 2,
                            IsActive = true,
                            LastSurName = "Çiftçi",
                            LockoutEnabled = false,
                            MiddleName = "Şenay",
                            Name = "Fatma",
                            NormalizedUserName = "FCIFTCI",
                            PasswordHash = "AQAAAAEAACcQAAAAEEapZkNkVHPHcMPc+r1ho9CSxOiRKvCk80Vz3s3GQkDHpm9bDrNXdtJs995FzQpgqQ==",
                            PhoneNumber = "12345678901",
                            PhoneNumberConfirmed = true,
                            Photo = "assets/images/PersonImages/3ff4d788-306e-401b-bb2e-5c61d6b6e5b6.png",
                            Salary = 25000.0,
                            SecurityStamp = "951dc27f-6021-4cd8-b916-18641df1b40e",
                            StartDateOfWork = new DateTime(2018, 4, 8, 10, 39, 3, 499, DateTimeKind.Local).AddTicks(6816),
                            Surname = "Yılmaz",
                            Title = 1,
                            TwoFactorEnabled = false,
                            UpdatedDate = new DateTime(2023, 4, 8, 10, 39, 3, 499, DateTimeKind.Local).AddTicks(6703),
                            UserName = "fciftci"
                        },
                        new
                        {
                            Id = "59323082792",
                            AccessFailedCount = 0,
                            Address = "adres kısmı",
                            AnnualPermit = 20,
                            Birthday = new DateTime(1989, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CompanyId = 1,
                            ConcurrencyStamp = "c452f3c8-5db5-469d-9547-fc33be3833ac",
                            CreateDate = new DateTime(2023, 4, 8, 10, 39, 3, 502, DateTimeKind.Local).AddTicks(5975),
                            Department = 1,
                            Email = "yuksel.guzel@bilgeadamboost.com",
                            EmailConfirmed = true,
                            Gender = 0,
                            Graduation = 2,
                            IsActive = true,
                            LastSurName = "",
                            LockoutEnabled = false,
                            MiddleName = "",
                            Name = "Yüksel",
                            NormalizedUserName = "YGUZEL",
                            PasswordHash = "AQAAAAEAACcQAAAAEDILdy2dhGbGalQwCBkv+bazyq9HGSUAu/ugqeeBylU5G4iuG1+7ChQ1a4BBUVGFdA==",
                            PhoneNumber = "05065385385",
                            PhoneNumberConfirmed = true,
                            Photo = "assets/images/PersonImages/3ff4d788-306e-401b-bb2e-5c61d6b6e5b6.png",
                            Salary = 25000.0,
                            SecurityStamp = "9759807b-aabe-43d5-9f65-e3b40f88feae",
                            StartDateOfWork = new DateTime(2018, 4, 8, 10, 39, 3, 502, DateTimeKind.Local).AddTicks(6004),
                            Surname = "Güzel",
                            Title = 1,
                            TwoFactorEnabled = false,
                            UpdatedDate = new DateTime(2023, 4, 8, 10, 39, 3, 502, DateTimeKind.Local).AddTicks(5975),
                            UserName = "yguzel"
                        });
                });

            modelBuilder.Entity("HR_T3.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            ConcurrencyStamp = "3837a14a-fcce-4c03-9563-e9ccd59ef491",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "projectmanager",
                            ConcurrencyStamp = "8fbe53a0-0fab-4eba-ac4e-d580f8c37bcb",
                            Name = "Project Manager",
                            NormalizedName = "PROJECT MANAGER"
                        },
                        new
                        {
                            Id = "employee",
                            ConcurrencyStamp = "b079724f-df9e-4cd3-be2e-4a0352b1cfc7",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "59323082791",
                            RoleId = "projectmanager"
                        },
                        new
                        {
                            UserId = "59323082792",
                            RoleId = "employee"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HR_T3.Domain.Entities.Cost", b =>
                {
                    b.HasOne("HR_T3.Domain.Entities.Person", "Person")
                        .WithMany("Costs")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HR_T3.Domain.Entities.Person", b =>
                {
                    b.HasOne("HR_T3.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("HR_T3.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HR_T3.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HR_T3.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("HR_T3.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_T3.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HR_T3.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR_T3.Domain.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HR_T3.Domain.Entities.Person", b =>
                {
                    b.Navigation("Costs");
                });
#pragma warning restore 612, 618
        }
    }
}
